export {default as about} from "./about.jpg"
export {default as Nike_Logo} from "./Nike-logo.jpg"
export {default as slider1} from "./banner1.jpg"
export {default as slider2} from "./banner2.jpg"
export {default as slider3} from "./banner3.jpg"
export {default as slider4} from "./banner4.jpg"
export {default as slider5} from "./banner5.jpg"